### ISSUE TITLE
Self maintained gitlab instances

### ISSUE THREAD

**Issue by thibautbenjamin** [wandersoncferreira/code-review#97]
First of, I would like to thank you for this package, this is a feature I have been wanting for a very long time. I hope to see this package become widely used, and I will surely use it as much as I can.
However, I am having some trouble for setting it up for a project with is hosted on a self-maintained gitlab instance. I managed to set it for forge and successfully downloaded the issues and PR by adding the following line to my `.authinfo.gpg` file
```
machine git.server.com/api/v4 login login^forge password ****
```
I tried various configuration lines for the `.authinfo.gpg` for code-review, but I tend to always get as a reply that I need to set a personal access token for gitlab.com. So in the end, I just wrote
```
machine gitlab.com/api login login^code-review password ****
```
This solves the previous issue, but now when I try calling calling `code-review-forge-pr-at-point` I get a message asking me for authentification (username and password). When after I type them, the function fails with the following messages
```
Fetch diff PR...100% 
deferred error : (wrong-type-argument sequencep char-or-string-p)
```
Honestly I am not too sure what's going on there, but my guess is that it is an authentification problem due to the fact that either I have not set up the authentification properly for my instance (I have nowhere given an authentification for `code-review` on `git.server.com`), or you do not support yet self-hosted gitlab instances. In the latter case, that's a feature I would be very interested in but no worries I completely understand if there are more requested features. Maybe I'll look into it and try to submit a PR around Christmas, but I have no prior knowledge about gitlab API so I am not sure how quickly I can achieve this. If it's just my mistake, maybe you could help me solve it and I can submit a PR with your explanation in the README.

Thanks again for the good work

**Comment by vlagorsse** [comment]
This looks like something close to the issue I reported some days ago: https://github.com/wandersoncferreira/code-review/issues/72

There was a release 0.0.3 containing fixes for this, I would suggest you to check the version of your package and share it here.

**Comment by thibautbenjamin** [comment]
Thanks for the pointer. I don't think it is the same issue, I use the straight package manager and I just checked, I am having this issue on the most recent commit on master `commit 2d38f18b5224e1de645c18f4f3034b07fc7df2dc`

**Comment by wandersoncferreira** [comment]
thanks for reporting the issue @thibautbenjamin , current version of the repo is not *totally* ready to support self-managed forges but its quite "easy" to fix, however I would like to discuss the issue further here:

1. the authentication issue should be fixed if you add a line like this in your authinfo:
```elisp
machine git.server.com/api login login^code-review password ****
```

2. I believe you should also do `(setq code-review-gitlab-host "git.server.com")`  and `(sets code-review-gitlab-graphql-host "git.server.com")`

These two steps should be enough to make `code-review` work if you use `code-review-forge-pr-at-point`.

The missing bit afaict is using `code-review-start` and providing a self managed PR URL, this will not work for now because this line is too naive to detect the right forge https://github.com/wandersoncferreira/code-review/blob/415f1e36607fff6c2fc937904aaecbd30e72d9b4/code-review-utils.el#L242 a PR to fix this function is necessary.

Could you make these changes and report back what the results are? Also, you should see more error logs in `~/.emacs.d/code-review-error.log` file.

**Comment by thibautbenjamin** [comment]
Thanks for your reply. It seems to be working with your workaround. I do not currently have any pending review, so I cannot really try it out now, but I will definitely try next time, and report if I encounter any further error.

I can make a PR adding a customization function to work with self-managed forges if you'd like. I imagine a way to handle them is to define a variable for storing the url of the forge, and customize it in the `.dir-locals.el` file, and modify the code slightly to take this in account. I should be able to send you a PR for this this weekend

**Comment by wandersoncferreira** [comment]
> Thanks for your reply. It seems to be working with your workaround. I do not currently have any pending review, so I cannot really try it out now, but I will definitely try next time, and report if I encounter any further error.

Nice! Great news.


> I can make a PR adding a customization function to work with self-managed forges if you'd like. I imagine a way to handle them is to define a variable for storing the url of the forge, and customize it in the `.dir-locals.el` file, and modify the code slightly to take this in account. I should be able to send you a PR for this this weekend

Yes, please. IMO would be great if we could use the existing `code-review-*-host` variables instead of new ones, for example in the public Github this is not possible as the API URL starts as `api.github.com` while the PR URL starts with `github.com`. Perhaps we could have a plist mapping pr-url to host-url similar to `forge-alist` (https://github.com/magit/forge/blob/4f72688d80b48e9c55c4e6d9540690c6641db530/lisp/forge-core.el#L54). wdyt?

**Comment by isamert** [comment]
I'm on version 0.0.4 and this issue is still exists (for me). I properly set the variables `code-review-gitlab-host`, `code-review-gitlab-graphql-host` and I also put my credentials to authinfo as required but I'm still getting the following when I call `code-review-forge-pr-at-point`:

```
Fetch diff PR...20% 
deferred error : (wrong-type-argument sequencep char-or-string-p)
```

The file `~/.emacs.d/code-review-error.log` only contains this:
```
Sun Dec 12 20:45:00 2021 - code-review--build-buffer - (wrong-type-argument char-or-string-p nil)
```

How can I debug this further? I'm not familiar with `deferred` and it's kinda making things hard to debug.

**Comment by askurihin** [comment]
I, sadly, have a similar error as @isamert:

```
Fetch diff PR...60% 
deferred error : (wrong-type-argument sequencep listp)
```
~/.emacs.d/code-review-error.log:

`Fri Dec 17 11:16:03 2021 - code-review--build-buffer - (wrong-type-argument listp wrong-number-of-arguments)`

Any debugging hints?

**Comment by wandersoncferreira** [comment]
sorry @isamert I missed your answer here. @askurihin if you both enable `toggle-debug-on-error` does it show a stack trace?

**Comment by askurihin** [comment]
Sadly, no, it does not show a stack trace :(

```
Debug on Error enabled globally
Fetch diff PR...20% 
deferred error : (wrong-type-argument sequencep listp)
```

**Comment by wandersoncferreira** [comment]
can you provide me more context about what you've done already @askurihin ? what values did you set for hosts, etc. (the pattern only not real value if its a problem to share)

**Comment by wandersoncferreira** [comment]
@askurihin can you update your package to the latest commit and `(setq code-review-log-raw-request-responses t)` so you can see the raw queries from your vc provider? For now the only queries logged are the two main ones required to load the buffer initially.

I will add a page in the docs with the expected result so you can also compare yourself (should be possible to run an `Ediff` on both files) if you don't want to paste it here for privacy reasons.

**Comment by wandersoncferreira** [comment]
The sample response structure: https://github.com/wandersoncferreira/code-review/blob/master/docs/response_samples.md

**Comment by askurihin** [comment]
@wandersoncferreira after I updated to the latest commit 79ae7fa `code-review-forge-pr-at-point` started working!
Thank you for the work!

**Comment by wandersoncferreira** [comment]
@isamert could you confirm that latest commit fixed for you too?

**Comment by isamert** [comment]
Just tried it out, it kinda works but it does not show any changes:

![image](https://user-images.githubusercontent.com/8031017/147108405-9e18345f-296e-46cb-bd43-cb52d2cab3c7.png)

For some PR's I get the following error:

```
Fetch diff PR...60% 
deferred error : (wrong-type-argument sequencep code-review-code-comment-section)
```

This error seems to appear when I try to view an MR that already has some comments inside.

I'll try with `(setq code-review-log-raw-request-responses t)` when I find some free time. But I guess these issues are not related to the ones defined in this issue, I can open a new one.

**Comment by wandersoncferreira** [comment]
Ok, @isamert let me know if you have more information on your issue. I am closing this issue for now.

**Comment by isamert** [comment]
Just to close the loop, it's been working quite fine for a while. I did upgrade some stuff after the error I mentioned and the issue just went away.
